# A GitHub Action that runs on every push to the grid-app branch and every pull request to the main branch. 
# It checks out the code, installs dependencies, and runs the tests.

name: Node.js CI

on:
  push:
    branches:
      - grid-app
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test
